// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcnPYahsjo5C2qVZ06Bkm10nXG8-ey6vo',
    appId: '1:1047085234746:web:2ab090cab4a5d6aed6d303',
    messagingSenderId: '1047085234746',
    projectId: 'gamecentermanager',
    authDomain: 'gamecentermanager.firebaseapp.com',
    storageBucket: 'gamecentermanager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIhEP6QxgKZTmTw7ydl3l9aN26LkCDjAY',
    appId: '1:1047085234746:android:5bcd10cddcfe2b20d6d303',
    messagingSenderId: '1047085234746',
    projectId: 'gamecentermanager',
    storageBucket: 'gamecentermanager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtB1C0xeLQIJvkAKvEm9S6YxwE9JqbG14',
    appId: '1:1047085234746:ios:bf6beb8f6f1f5afed6d303',
    messagingSenderId: '1047085234746',
    projectId: 'gamecentermanager',
    storageBucket: 'gamecentermanager.firebasestorage.app',
    iosBundleId: 'com.gamecenter.app.gameCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtB1C0xeLQIJvkAKvEm9S6YxwE9JqbG14',
    appId: '1:1047085234746:ios:bf6beb8f6f1f5afed6d303',
    messagingSenderId: '1047085234746',
    projectId: 'gamecentermanager',
    storageBucket: 'gamecentermanager.firebasestorage.app',
    iosBundleId: 'com.gamecenter.app.gameCenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcnPYahsjo5C2qVZ06Bkm10nXG8-ey6vo',
    appId: '1:1047085234746:web:81384e2ddf0a2253d6d303',
    messagingSenderId: '1047085234746',
    projectId: 'gamecentermanager',
    authDomain: 'gamecentermanager.firebaseapp.com',
    storageBucket: 'gamecentermanager.firebasestorage.app',
  );
}
